/*
Kristofer Hughes
CSC 355 Section 402 
Assignment 4
October 13th, 2019 
*/

/*
Query 1
*/

SELECT CONCAT(CONCAT(FIRSTNAME, ' '),lastname) as FULLNAME, INSURANCE 
from PATIENT INNER JOIN DOCTOR ON PATIENT.DOCTORID = DOCTOR.ID
WHERE MEDICALGROUP = 281;

/*
Query 2
*/

SELECT count(Description), ROUND(AVG(COST),2) AS AVERAGECOST
FROM PROCEDURE 
WHERE COST > 1000;


/*
Query 3
*/

Select INSURANCE, COUNT(PID) as VISITCOUNT
from PATIENT INNER JOIN VISIT ON PATIENT.ID = VISIT.PID
GROUP by Insurance;

/*
Query 4
*/

SELECT SUM(COST)
from PATIENT inner join SCHEDULE on PATIENT.ID = SCHEDULE.PID 
inner join PROCEDURE on PROCEDURE.CODE = SCHEDULE.PCODE 
where PID = 6776775;

/*
Query 5
*/

SELECT DOCTORID, NAME, AVG(AGE)
from PATIENT INNER JOIN DOCTOR ON PATIENT.DOCTORID = DOCTOR.ID
WHERE INSURANCE = 'HMO Illinois'
group by DoctorID, Name;

/*
Query 6
*/

Select PID, CONCAT(CONCAT(FIRSTNAME, ' '),lastname) as FULLNAME
from PATIENT INNER JOIN VISIT ON PATIENT.ID = VISIT.PID
where ADMISSIONDATE <= '30-SEP-19' AND (DISCHARGEDATE >= '30-SEP-19' OR DISCHARGEDATE IS NULL);


/*
Query 7
*/

SELECT PROCEDURE.DESCRIPTION, CONCAT(CONCAT(FIRSTNAME, ' '),lastname) as FULLNAME, PID
from SCHEDULE inner join PATIENT on SCHEDULE.PID = PATIENT.ID 
inner join PROCEDURE on PROCEDURE.CODE = SCHEDULE.PCODE 
where SCHEDULE.PROCEDUREDATE = '12-OCT-19';


/*
Query 8
*/

Select DESCRIPTION, SUM(COST) AS TOTALINCOME
from PROCEDURE INNER JOIN SCHEDULE ON PROCEDURE.CODE = SCHEDULE.PCODE
Group by Description
ORDER by TOTALINCOME ASC;
